version: '3'

services:

  app:
    image: jmendej/desafio1-node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks: 
      - frontend-networks
      - backend-networks
    depends_on: 
      - db  

  proxy:
    image: jmendej/desafio1-ngnix
    container_name: proxy
    networks: 
      - frontend-networks
    ports: 
      - "8080:80"
    depends_on: 
      - app     

  db:
    image: jmendej/desafio1-mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment: 
      - MYSQL_DATABASE=db_app
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - backend-networks
    
networks: 
  frontend-networks:
    name: frontend-networks
    driver: bridge
  backend-networks:
    name: backend-networks
    driver: bridge  