version: '3'

services:

  app:
    build: 
      context: node
    container_name: app
    networks: 
      - frontend-networks

  proxy:
    build:
      context: ngnix
    container_name: proxy
    networks: 
      - frontend-networks
    ports: 
      - "8080:80"  

networks: 
  frontend-networks:
    name: frontend-networks
    driver: bridge